name: 'Services Autoconfigure Example'
type: module
description: 'An example of autoconfiguring a service.'
package: Example
core_version_requirement: ^10 || ^11
dependencies:
  - drupal_services_examples:drupal_services_examples
